### ISSUE TITLE
Crashes when searching after binding with "behave"

### ISSUE THREAD

**Issue by lamby** [jordansissel/xdotool#169]
Via https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=858221:

```
I'm trying to bind a "search" command for another window when (say) an
MPlayer window is focused:

 $ xdotool search --name MPlayer behave %@ focus \
     search --name . getwindowname

However, xdotool segfaults upon focusing Mplayer:

(gdb) run search --name MPlayer behave %@ focus search --name . getwindowname
Starting program: /usr/bin/xdotool search --name MPlayer behave %@ focus search --name . getwindowname
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
*** Error in `/usr/bin/xdotool': double free or corruption (out): 0x00007fffffffe3a0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bcb)[0x7ffff7053bcb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76f96)[0x7ffff7059f96]
/lib/x86_64-linux-gnu/libc.so.6(+0x7778e)[0x7ffff705a78e]
/usr/bin/xdotool(+0x8432)[0x55555555c432]
/usr/bin/xdotool(+0x413f)[0x55555555813f]
/usr/bin/xdotool(+0x9f8d)[0x55555555df8d]
/usr/bin/xdotool(+0x413f)[0x55555555813f]
/usr/bin/xdotool(+0x4a70)[0x555555558a70]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7ffff70032b1]
/usr/bin/xdotool(+0x3a6a)[0x555555557a6a]
======= Memory map: ========
555555554000-555555565000 r-xp 00000000 08:01 1835027                    /usr/bin/xdotool
555555765000-555555766000 r--p 00011000 08:01 1835027                    /usr/bin/xdotool
555555766000-555555768000 rw-p 00012000 08:01 1835027                    /usr/bin/xdotool
555555768000-5555557ab000 rw-p 00000000 00:00 0                          [heap]
7ffff0000000-7ffff0021000 rw-p 00000000 00:00 0 
7ffff0021000-7ffff4000000 ---p 00000000 00:00 0 
7ffff56f8000-7ffff570e000 r-xp 00000000 08:01 5505262                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff570e000-7ffff590d000 ---p 00016000 08:01 5505262                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff590d000-7ffff590e000 r--p 00015000 08:01 5505262                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff590e000-7ffff590f000 rw-p 00016000 08:01 5505262                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff590f000-7ffff5922000 r-xp 00000000 08:01 5505236                    /lib/x86_64-linux-gnu/libbsd.so.0.8.3
7ffff5922000-7ffff5b22000 ---p 00013000 08:01 5505236                    /lib/x86_64-linux-gnu/libbsd.so.0.8.3
7ffff5b22000-7ffff5b23000 r--p 00013000 08:01 5505236                    /lib/x86_64-linux-gnu/libbsd.so.0.8.3
7ffff5b23000-7ffff5b24000 rw-p 00014000 08:01 5505236                    /lib/x86_64-linux-gnu/libbsd.so.0.8.3
7ffff5b24000-7ffff5b25000 rw-p 00000000 00:00 0 
7ffff5b25000-7ffff5b2a000 r-xp 00000000 08:01 1836637                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7ffff5b2a000-7ffff5d29000 ---p 00005000 08:01 1836637                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7ffff5d29000-7ffff5d2a000 r--p 00004000 08:01 1836637                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7ffff5d2a000-7ffff5d2b000 rw-p 00005000 08:01 1836637                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7ffff5d2b000-7ffff5d2e000 r-xp 00000000 08:01 1841451                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7ffff5d2e000-7ffff5f2d000 ---p 00003000 08:01 1841451                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7ffff5f2d000-7ffff5f2e000 r--p 00002000 08:01 1841451                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7ffff5f2e000-7ffff5f2f000 rw-p 00003000 08:01 1841451                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7ffff5f2f000-7ffff5f3e000 r-xp 00000000 08:01 1839502                    /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
7ffff5f3e000-7ffff613d000 ---p 0000f000 08:01 1839502                    /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
7ffff613d000-7ffff613e000 r--p 0000e000 08:01 1839502                    /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
7ffff613e000-7ffff613f000 rw-p 0000f000 08:01 1839502                    /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
7ffff613f000-7ffff6150000 r-xp 00000000 08:01 1836653                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7ffff6150000-7ffff634f000 ---p 00011000 08:01 1836653                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7ffff634f000-7ffff6350000 r--p 00010000 08:01 1836653                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7ffff6350000-7ffff6351000 rw-p 00011000 08:01 1836653                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7ffff6351000-7ffff6369000 r-xp 00000000 08:01 5505619                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7ffff6369000-7ffff6568000 ---p 00018000 08:01 5505619                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7ffff6568000-7ffff6569000 r--p 00017000 08:01 5505619                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7ffff6569000-7ffff656a000 rw-p 00018000 08:01 5505619                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7ffff656a000-7ffff656e000 rw-p 00000000 00:00 0 
7ffff656e000-7ffff6570000 r-xp 00000000 08:01 5505329                    /lib/x86_64-linux-gnu/libdl-2.24.so
7ffff6570000-7ffff6770000 ---p 00002000 08:01 5505329                    /lib/x86_64-linux-gnu/libdl-2.24.so
7ffff6770000-7ffff6771000 r--p 00002000 08:01 5505329                    /lib/x86_64-linux-gnu/libdl-2.24.so
7ffff6771000-7ffff6772000 rw-p 00003000 08:01 5505329                    /lib/x86_64-linux-gnu/libdl-2.24.so
7ffff6772000-7ffff6799000 r-xp 00000000 08:01 1839985                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7ffff6799000-7ffff6998000 ---p 00027000 08:01 1839985                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7ffff6998000-7ffff6999000 r--p 00026000 08:01 1839985                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7ffff6999000-7ffff699a000 rw-p 00027000 08:01 1839985                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7ffff699a000-7ffff69d8000 r-xp 00000000 08:01 1836120                    /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0
7ffff69d8000-7ffff6bd7000 ---p 0003e000 08:01 1836120                    /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0
7ffff6bd7000-7ffff6bd9000 r--p 0003d000 08:01 1836120                    /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0
7ffff6bd9000-7ffff6bda000 rw-p 0003f000 08:01 1836120                    /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0
7ffff6bda000-7ffff6bdc000 r-xp 00000000 08:01 1850198                    /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7ffff6bdc000-7ffff6ddb000 ---p 00002000 08:01 1850198                    /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7ffff6ddb000-7ffff6ddc000 r--p 00001000 08:01 1850198                    /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7ffff6ddc000-7ffff6ddd000 rw-p 00002000 08:01 1850198                    /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7ffff6ddd000-7ffff6de2000 r-xp 00000000 08:01 1841085                    /usr/lib/x86_64-linux-gnu/libXtst.so.6.1.0
7ffff6de2000-7ffff6fe1000 ---p 00005000 08:01 1841085                    /usr/lib/x86_64-linux-gnu/libXtst.so.6.1.0
7ffff6fe1000-7ffff6fe2000 r--p 00004000 08:01 1841085                    /usr/lib/x86_64-linux-gnu/libXtst.so.6.1.0
7ffff6fe2000-7ffff6fe3000 rw-p 00005000 08:01 1841085                    /usr/lib/x86_64-linux-gnu/libXtst.so.6.1.0
7ffff6fe3000-7ffff7178000 r-xp 00000000 08:01 5505178                    /lib/x86_64-linux-gnu/libc-2.24.so
7ffff7178000-7ffff7377000 ---p 00195000 08:01 5505178                    /lib/x86_64-linux-gnu/libc-2.24.so
7ffff7377000-7ffff737b000 r--p 00194000 08:01 5505178                    /lib/x86_64-linux-gnu/libc-2.24.so
7ffff737b000-7ffff737d000 rw-p 00198000 08:01 5505178                    /lib/x86_64-linux-gnu/libc-2.24.so
7ffff737d000-7ffff7381000 rw-p 00000000 00:00 0 
7ffff7381000-7ffff7388000 r-xp 00000000 08:01 5505626                    /lib/x86_64-linux-gnu/librt-2.24.so
7ffff7388000-7ffff7587000 ---p 00007000 08:01 5505626                    /lib/x86_64-linux-gnu/librt-2.24.so
7ffff7587000-7ffff7588000 r--p 00006000 08:01 5505626                    /lib/x86_64-linux-gnu/librt-2.24.so
7ffff7588000-7ffff7589000 rw-p 00007000 08:01 5505626                    /lib/x86_64-linux-gnu/librt-2.24.so
7ffff7589000-7ffff76c3000 r-xp 00000000 08:01 1840036                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7ffff76c3000-7ffff78c3000 ---p 0013a000 08:01 1840036                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7ffff78c3000-7ffff78c4000 r--p 0013a000 08:01 1840036                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7ffff78c4000-7ffff78c9000 rw-p 0013b000 08:01 1840036                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7ffff78c9000-7ffff79cc000 r-xp 00000000 08:01 5505393                    /lib/x86_64-linux-gnu/libm-2.24.so
7ffff79cc000-7ffff7bcb000 ---p 00103000 08:01 5505393                    /lib/x86_64-linux-gnu/libm-2.24.so
7ffff7bcb000-7ffff7bcc000 r--p 00102000 08:01 5505393                    /lib/x86_64-linux-gnu/libm-2.24.so
7ffff7bcc000-7ffff7bcd000 rw-p 00103000 08:01 5505393                    /lib/x86_64-linux-gnu/libm-2.24.so
7ffff7bcd000-7ffff7bd8000 r-xp 00000000 08:01 1835587                    /usr/lib/x86_64-linux-gnu/libxdo.so.3
7ffff7bd8000-7ffff7dd7000 ---p 0000b000 08:01 1835587                    /usr/lib/x86_64-linux-gnu/libxdo.so.3
7ffff7dd7000-7ffff7dd8000 r--p 0000a000 08:01 1835587                    /usr/lib/x86_64-linux-gnu/libxdo.so.3
7ffff7dd8000-7ffff7dd9000 rw-p 0000b000 08:01 1835587                    /usr/lib/x86_64-linux-gnu/libxdo.so.3
7ffff7dd9000-7ffff7dfc000 r-xp 00000000 08:01 5505047                    /lib/x86_64-linux-gnu/ld-2.24.so
7ffff7fd3000-7ffff7fdb000 rw-p 00000000 00:00 0 
7ffff7ff4000-7ffff7ff8000 rw-p 00000000 00:00 0 
7ffff7ff8000-7ffff7ffa000 r--p 00000000 00:00 0                          [vvar]
7ffff7ffa000-7ffff7ffc000 r-xp 00000000 00:00 0                          [vdso]
7ffff7ffc000-7ffff7ffd000 r--p 00023000 08:01 5505047                    /lib/x86_64-linux-gnu/ld-2.24.so
7ffff7ffd000-7ffff7ffe000 rw-p 00024000 08:01 5505047                    /lib/x86_64-linux-gnu/ld-2.24.so
7ffff7ffe000-7ffff7fff000 rw-p 00000000 00:00 0 
7ffffffde000-7ffffffff000 rw-p 00000000 00:00 0                          [stack]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
58	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007ffff701740a in __GI_abort () at abort.c:89
#2  0x00007ffff7053bd0 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff7148c30 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff7059f96 in malloc_printerr (action=3, str=0x7ffff7148cf8 "double free or corruption (out)", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5046
#4  0x00007ffff705a78e in _int_free (av=0x7ffff737bb00 <main_arena>, p=0x7fffffffe390, have_lock=0) at malloc.c:3902
#5  0x000055555555c432 in cmd_search (context=0x7fffffffe330) at cmd_search.c:204
#6  0x000055555555813f in context_execute (context=context@entry=0x7fffffffe330) at xdotool.c:586
#7  0x000055555555df8d in cmd_behave (context=0x7fffffffe4e0) at cmd_behave.c:145
#8  0x000055555555813f in context_execute (context=0x7fffffffe4e0) at xdotool.c:586
#9  0x0000555555558a70 in args_main (argv=<optimized out>, argc=10) at xdotool.c:559
#10 xdotool_main (argc=11, argv=0x7fffffffe6d8) at xdotool.c:317
#11 0x00007ffff70032b1 in __libc_start_main (main=0x555555557a30 <main>, argc=11, argv=0x7fffffffe6d8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffe6c8) at ../csu/libc-start.c:291
#12 0x0000555555557a6a in _start ()


(The same happens if I bind to blur instead of focus.)
```

**Comment by jordansissel** [comment]
I'll see if I can reproduce this. It looks like a bug.

**Comment by adelton** [comment]
@jordansissel Is https://github.com/jordansissel/xdotool/issues/194#issuecomment-885390745 something that might be relevant?
