### ISSUE TITLE
Cannot run tests: undefined method `_run_suite' for class `Test::Unit::Runner' (NameError)

### ISSUE THREAD

**Issue by blueyed** [jordansissel/xdotool#54]
I have tried to run the tests, but it fails:

```
Running test_basic.rb
Warning: Tried to connect to session manager, Could not open network socket
Setting up keymap on new server as us
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /usr/lib/ruby/2.1.0/test/unit.rb:1:in `<top (required)>'
  test_basic.rb:4:in `<main>'
MiniTest::Unit::TestCase is now Minitest::Test. From /usr/lib/ruby/2.1.0/test/unit/testcase.rb:8:in `<module:Unit>'
/usr/lib/ruby/2.1.0/test/unit.rb:676:in `<class:Runner>': undefined method `_run_suite' for class `Test::Unit::Runner' (NameError)
  from /usr/lib/ruby/2.1.0/test/unit.rb:261:in `<module:Unit>'
  from /usr/lib/ruby/2.1.0/test/unit.rb:15:in `<module:Test>'
  from /usr/lib/ruby/2.1.0/test/unit.rb:7:in `<top (required)>'
  from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from test_basic.rb:4:in `<main>'
make[3]: *** [do-test] Error 1
make[3]: Leaving directory `/home/daniel/Vcs/xdotool/t'

% ruby --version
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
```

What am I missing?

Is my Ruby stack too new? (`MiniTest::Unit::TestCase is now Minitest::Test`)

**Comment by kyawsanwin** [comment]
I also found that problem. But, I can fix it by installing ruby 1.9.

Ruby 1.9.x bundles minitest not Test::Unit. Test::Unit bundled in Ruby 1.8.x had not been improved but unbundled Test::Unit (test-unit) is improved actively.

I found that on it. http://stackoverflow.com/questions/25713491/ruby-undefined-method-run-suite-for-class-testunitrunner.

**Comment by duboviy** [comment]
Try with minitest 4.7.5 version
