### ISSUE TITLE
[Xtightvnc] Segfault

### ISSUE THREAD

**Issue by fzg** [jordansissel/xdotool#58]
Hey. I'm no X11 guru, so this is possibly an issue with Xtightvnc. Is it?

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bd7e8f in _xdo_populate_charcode_map (xdo=0x61ba80) at xdo.c:1304
$1 = (XkbDescPtr) 0x0
$2 = 8

(gdb) where
#0  0x00007ffff7bd7e8f in _xdo_populate_charcode_map (xdo=0x61ba80) at xdo.c:1304
#1  xdo_new_with_opened_display (xdpy=<optimized out>, display=<optimized out>, close_display_when_freed=close_display_when_freed@entry=1) at xdo.c:133
#2  0x00007ffff7bd80a1 in xdo_new (display_name=<optimized out>, display_name@entry=0x0) at xdo.c:95
#3  0x000000000040319e in args_main (argc=argc@entry=4, argv=argv@entry=0x7fffffffe668) at xdotool.c:493
#4  0x0000000000403724 in xdotool_main (argc=4, argv=0x7fffffffe668) at xdotool.c:316

So we got an unhandled NULL coming from XkbGetMap() :-(

Xvnc version TightVNC-1.3.9
Linux xxxx 3.2.0-4-amd64 #1 SMP Debian 3.2.60-1+deb7u3 x86_64 GNU/Linux
xdotool/libxd built minutes ago from HEAD.

**Comment by jordansissel** [comment]
Definitely sounds like a bug. I'll try to reproduce with Xtightvnc next time I get the chance.

**Comment by stayprivate** [comment]
Jumping in this old bug... Got the issue, trace it to XkbGetMap in _xdo_populate_charcode_map returning a null pointer. I added a if that skips the for loops, it stops the crash, but things like Ctrl+Shift+T don't work.  I can see a t, show up on the console though.  At this point I'm stump.

**Comment by stayprivate** [comment]
Forget it found more recent issue
