### ISSUE TITLE
SIGSEGV at xdo_new_with_opened_display() under Xvnc4

### ISSUE THREAD

**Issue by kenorb** [jordansissel/xdotool#75]
I've Segmentation fault when using X virtual framebuffer almost for every command.

Version installed from `apt-get`: `1:3.20140805.1-2`.

Example:

    $ DISPLAY=:1 xdotool search foo
    Segmentation fault (core dumped)

Backstrace:

    #0  0x00007ffff7bd40cf in xdo_new_with_opened_display () from /usr/lib/x86_64-linux-gnu/libxdo.so.3
    #1  0x00000000004032be in ?? ()
    #2  0x0000000000403884 in ?? ()
    #3  0x00007ffff6fdaa40 in __libc_start_main (main=0x402980, argc=3, argv=0x7fffffffe5b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe5a8) at libc-start.c:289

I can't compile with debug symbols to provide full bt, because of #48.

Reproducible steps:

1. Install `vagrant`.
2. Create the following `Vagrantfile` file in empty folder:

        Vagrant.configure(2) do |config|
          config.vm.box = "ubuntu/vivid64"
          config.vm.box_version = "20150722.0.0"
        end

3. Run: `vagrant up && vagrant ssh`.
4. In VM, install Xvfb, xdotool and vnc4server:

        sudo apt-get install Xvfb xdotool vnc4server

5. Run Xvfb: `Xvfb :0 -screen 0 1024x768x16 &`
6. Run: `DISPLAY=:0 xdotool search foo` -> somehow this works.
7. Now run VNC: `Xvnc4 :1 &`
8. Now run:

        $ DISPLAY=:1 xdotool search foo
        Segmentation fault (core dumped)

This seems to be related to #58.

**Comment by kenorb** [comment]
Yes, it's the same thing.

```
(gdb) bt full
#0  0x00007ffff7bd2bb9 in _xdo_populate_charcode_map (xdo=0x61fdb0) at xdo.c:1304
        keycodes_length = 496
        idx = 0
        keycode = 8
        group = 0
        groups = 0
        level = 0
        modmask = -7504
        num_map = 32767
        keysyms = 0x620770
        desc = 0x0
#1  0x00007ffff7bcf903 in xdo_new_with_opened_display (xdpy=0x615010, display=0x7fffffffef96 ":1", close_display_when_freed=1) at xdo.c:133
        xdo = 0x61fdb0
#2  0x00007ffff7bcf7cb in xdo_new (display_name=0x7fffffffef96 ":1") at xdo.c:95
        xdpy = 0x615010
```

**Comment by hilbix** [comment]
```
diff --git a/xdo.c b/xdo.c
index 8128d83..e6d698e 100644
--- a/xdo.c
+++ b/xdo.c
@@ -1299,6 +1299,7 @@ static void _xdo_populate_charcode_map(xdo_t *xdo) {
 
   xdo->charcodes = calloc(keycodes_length, sizeof(charcodemap_t));
   XkbDescPtr desc = XkbGetMap(xdo->xdpy, XkbAllClientInfoMask, XkbUseCoreKbd);
+  if (!desc) return;
 
   for (keycode = xdo->keycode_low; keycode <= xdo->keycode_high; keycode++) {
     groups = XkbKeyNumGroups(desc, keycode);
```

**Comment by jordansissel** [comment]
Hmm, is the problem that Xvnc4 doesn't support xkbcommon? If this is the case, I'm not sure xdotool keyboard commands (type, key, etc) will work :\

I agree it shouldn't crash though.

**Comment by joluinfante** [comment]
Hi! Any workaround for this?

**Comment by Steve-Newcomb** [comment]
*bump*
I just ran into this again.  A workaround would be very nice.  Is there even a firm diagnosis yet?

**Comment by jordansissel** [comment]
The diagnosis is that xkbcommon is unsupported by your vnc server and
xdotool is crashing because of it.

It's a bug that can be fixed but I don't know how complex it might be.
